### ISSUE TITLE
papirus icon in panel?

### ISSUE THREAD

**Issue by np1729** [Rokin05/nocturnal-kde#1]
your themes are awesome but can we set papirus icon in panel??
![screenshot_20180428_111537](https://user-images.githubusercontent.com/38804205/39392570-9113e908-4ad5-11e8-9eb3-5eae2c9ef567.png)

**Comment by Rokin05** [comment]
Hi and sorry for the delay !

Papirus/Nocturnal/Breeze icons in app bar is a part of "Plasma Theme". The panel icons are located at : `/usr/share/plasma/desktoptheme/Nocturnal/icons/`

Nocturnal is not a "fork" of a papirus theme like Arc or Materia theme (from the creator of papyrus icons-pack) but use the Breeze icons.

If you absolutely want use "Papirus" icons, you can try to mix Nocturnal (Plasma theme) with the icons of Adapta (Plasma theme) but i do not garantee the visual result and a update of Nocturnal can break this manual modification :

```
cd /tmp

#Download a copy of Adapta theme
git clone https://github.com/PapirusDevelopmentTeam/adapta-kde

#Move Nocturnal icon to a "save directory"
mv /usr/share/plasma/desktoptheme/Nocturnal/icons /usr/share/plasma/desktoptheme/Nocturnal/icons.save

#Copy Adapta icons to Nocturnal theme 
cp -r adapta-kde/plasma/desktoptheme/Adapta/icons /usr/share/plasma/desktoptheme/Nocturnal/icons

#Remove Adapta theme previously donwloaded (not used)
rm -R /tmp/adapta-kde
```

for reverse back :
```
#Remove Nocturnal icons folder (cf: Adapta icons)
rm -R /usr/share/plasma/desktoptheme/Nocturnal/icons

#Rename "icons.save" folder to "icons" folder (Nocturnal save icons)
mv /usr/share/plasma/desktoptheme/Nocturnal/icons.old /usr/share/plasma/desktoptheme/Nocturnal/icons
```
