### ISSUE TITLE
Transparent sharp edges?

### ISSUE THREAD

**Issue by DrNuget** [Rokin05/nocturnal-kde#3]
I downloaded nocturnal theme from kde website and there are these "sharp edges" around all windows.
![image](https://user-images.githubusercontent.com/34383935/47390111-3f414400-d71f-11e8-8c95-19b12cf824e9.png)

**Comment by blackICE19240** [comment]
What do you mean? It's hard to see from the picture.

**Comment by DrNuget** [comment]
> What do you mean? It's hard to see from the picture.

It's hard to explain, but if you zoom in to the picture you can see a box surrounding whats is supposed to be the theme, this doesn't happen on other themes.
